---
  - action: uri url=http://10.133.21.217:49998/springwebapp/car/add return_content=yes
    register: webpage

  - fail: msg='service is not happy'
    when: "'Add a car' not in webpage.content"
  
  - shell: date
    register: cmd_result

  - assert:
       that:
       - "'UTC 2017' in cmd_result.stdout"  

  - stat: path=/var/lib/tomcat8/webapps/springwebapp.war
    register: p

