---
  - action: uri url=http://localhost/index.html return_content=yes
    register: webpage

  - fail: msg='service is not happy'
    when: "'Manjyot' not in webpage.content"
  
  - shell: date
    register: cmd_result

  - assert:
       that:
       - "'IST 2017' in cmd_result.stdout"  

  - stat: path=/var/www/html/index.html
    register: p

  - assert:
       that:
       - p.stat.exists
